### ISSUE TITLE
Segfault when running

### ISSUE THREAD

**Issue by dtgriscom** [mmiranda/markdown-index#10]
Running on macOS 10.14.6. Installed using

```
brew tap mmiranda/mdindex
brew install markdown-index
```

Ran in directory tree holding a bunch of .md files. Ran for 11 seconds, and then segfaulted:

```
mbpe-ethernet:dev griscom$ markdown-index
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x125c5db]

goroutine 1 [running]:
github.com/mmiranda/markdown-index/markdown.(*rawMarkdown).getFirstParagraph.func1({0x13e9390, 0xc00035a750}, 0x0)
	/home/runner/work/markdown-index/markdown-index/markdown/markdown.go:176 +0x19b
github.com/yuin/goldmark/ast.walkHelper({0x13e9390, 0xc00035a750}, 0xc0000afba0)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:492 +0x34
github.com/yuin/goldmark/ast.walkHelper({0x13e9810, 0xc00035a6c0}, 0xc0000afba0)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.walkHelper({0x13e96f0, 0xc00035a630}, 0xc0000afba0)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.walkHelper({0x13e8f10, 0xc00035a120}, 0xc0000afba0)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:487
github.com/mmiranda/markdown-index/markdown.(*rawMarkdown).getFirstParagraph(0xc000482210)
	/home/runner/work/markdown-index/markdown-index/markdown/markdown.go:167 +0x9d
github.com/mmiranda/markdown-index/markdown.buildIndexContent({0x133d50e, 0x12baea5}, {0x0, 0xc00021fda0, 0xc00021fdc8})
	/home/runner/work/markdown-index/markdown-index/markdown/markdown.go:269 +0x227
github.com/mmiranda/markdown-index/markdown.Execute({0x1343ed8, 0x11}, {0x133d50e, 0x1})
	/home/runner/work/markdown-index/markdown-index/markdown/markdown.go:47 +0x52
github.com/mmiranda/markdown-index/cmd.glob..func1(0x159ca00, {0x133df65, 0x0, 0x0})
	/home/runner/work/markdown-index/markdown-index/cmd/root.go:24 +0x35
github.com/spf13/cobra.(*Command).execute(0x159ca00, {0xc000010200, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x159ca00)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/mmiranda/markdown-index/cmd.Execute()
	/home/runner/work/markdown-index/markdown-index/cmd/root.go:47 +0x25
main.main()
	/home/runner/work/markdown-index/markdown-index/main.go:6 +0x17
```

**Comment by mmiranda** [comment]
Interesting issue @dtgriscom 

Would you mind updating to version `0.1.1` and using the `--debug` flag to understand which file is breaking?
I guess that this file could have some differences that the indexer is struggling with. 

I'd love to fix that issue, once you have identified the file, please reach back to me and I can troubleshoot better in the code.

**Comment by jmoleiro** [comment]
Hi i used the option --debug and noted on error if the file looks like this

```md
# Title

Description

## Subtitle

```
When I completeed the file like this, the error vanishes and the index file was generated without problems

```md
# Title

Description

## Subtitle

Some text here

```

**Comment by dtgriscom-ta** [comment]
Sorry about the long delay...

I've duplicated the problem with version 0.1.1, and it looks like it's a specific file that causes the problem. After some successive approximation and subdivision, I narrowed the problem down to four lines:

```
# XML Types

- ### int8 through int64 (and uint versions)

```
To duplicate:
- Create an empty directory
- Create a test.md file with the above contents
- Run `markdown-index --debug`

and boom:

```
mbpe-ethernet:delme griscom$ markdown-index --debug
DEBU[0000] Reading file: ._test.md                      
DEBU[0000] Reading file: test.md                        
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x110 pc=0x1275c3b]

goroutine 1 [running]:
github.com/mmiranda/markdown-index/markdown.(*rawMarkdown).getFirstParagraph.func1({0x13facb0, 0xc00016ee10}, 0x0)
	/home/runner/work/markdown-index/markdown-index/markdown/markdown.go:183 +0x19b
github.com/yuin/goldmark/ast.walkHelper({0x13facb0, 0xc00016ee10}, 0xc00021fb90)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:492 +0x34
github.com/yuin/goldmark/ast.walkHelper({0x13fb130, 0xc00016ed80}, 0xc00021fb90)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.walkHelper({0x13fb010, 0xc00016ecf0}, 0xc00021fb90)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.walkHelper({0x13fa830, 0xc00016ebd0}, 0xc00021fb90)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:498 +0x8e
github.com/yuin/goldmark/ast.Walk(...)
	/home/runner/go/pkg/mod/github.com/yuin/goldmark@v1.4.1/ast/ast.go:487
github.com/mmiranda/markdown-index/markdown.(*rawMarkdown).getFirstParagraph(0xc0001946c0)
	/home/runner/work/markdown-index/markdown-index/markdown/markdown.go:174 +0xa5
github.com/mmiranda/markdown-index/markdown.buildIndexContent({0x134cecd, 0x12d4365}, {0x0, 0xc00021fda0, 0xc00021fdc8})
	/home/runner/work/markdown-index/markdown-index/markdown/markdown.go:277 +0x287
github.com/mmiranda/markdown-index/markdown.Execute({0x1353920, 0x11}, {0x134cecd, 0x1})
	/home/runner/work/markdown-index/markdown-index/markdown/markdown.go:54 +0x65
github.com/mmiranda/markdown-index/cmd.glob..func1(0x15b9c20, {0x134d92d, 0x1, 0x1})
	/home/runner/work/markdown-index/markdown-index/cmd/root.go:31 +0x48
github.com/spf13/cobra.(*Command).execute(0x15b9c20, {0xc0000b6010, 0x1, 0x1})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x15b9c20)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/mmiranda/markdown-index/cmd.Execute()
	/home/runner/work/markdown-index/markdown-index/cmd/root.go:54 +0x25
main.main()
	/home/runner/work/markdown-index/markdown-index/main.go:6 +0x17
mbpe-ethernet:delme griscom$ 
```

**Comment by mmiranda** [comment]
Thank you @jmoleiro and @dtgriscom-ta 

As I see it, both issues are related and it happens when the file has a heading without any text under it.

You can try again using the `v0.1.2`
